# -*- coding: utf-8 -*-
"""Average of a vector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1chKs3AiTUfZqtD9dinX3Y2nUN6GJ77CK
"""

## This code will calculate the average of any vector colleting input form user

#Taking vector inputs
vector_list = []
n = int (input("Enter the list size "))

print("\n")

#Loop for user friendly input interface
for i in range(0, n):
    print("Enter number at index", i, )
    item = int(input())
    vector_list.append(item)

#Average is calculated here
avg = sum(vector_list)/len(vector_list)

#Print out the final result with the input vector
print("User input vector is ", vector_list)
print("The average is ", round(avg,2))

